export const VALIDATION = {
  PRODUCT: {
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 255,
    SLUG_MIN_LENGTH: 2,
    SLUG_MAX_LENGTH: 255,
    SLUG_PATTERN: /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
    DESCRIPTION_MAX_LENGTH: 2000,
    SHORT_DESCRIPTION_MAX_LENGTH: 500,
  },
  CATEGORY: {
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 100,
  },
  VARIANT: {
    NAME_MIN_LENGTH: 1,
    NAME_MAX_LENGTH: 100,
    SKU_MIN_LENGTH: 3,
    SKU_MAX_LENGTH: 100,
    SKU_PATTERN: /^[A-Z0-9\-_]+$/,
    PRICE_MIN: 0,
    PRICE_MAX: 1000000,
    STOCK_MIN: 0,
    STOCK_MAX: 1000000,
    UNIT_VALUE_MIN: 0.001,
    UNIT_VALUE_MAX: 10000,
  },
} as const;
